name: Update bedbase genomes table

on:
  schedule:
  - cron: '0 0 * * 2' # every Tuesday at midnight
  workflow_dispatch:
    inputs: null

jobs:
  update_genomes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install torch==2.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html --system
        uv pip install bedboss --system

    - name: Update umap
      run: |
        bedboss update-genomes --config config.yaml

    - name: Commit report
      run: |
        git config --global user.name 'Oleksandr Khoroshevskyi'
        git config --global user.email 'khoroshevskyi@users.noreply.github.com'
        git add -A
        git commit -m "Automated update of number of files"
        git push
