name: Upload one gse

on:
  workflow_dispatch:
    inputs:
      gse:
        description: 'gse number. ["GSE12345"]'
        required: true


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.12" ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install torch==2.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
          uv pip install git+https://github.com/databio/bedboss.git@partial_processing#egg=bedboss --system

      - name: Do something here
        run: |
            echo "Hello, ${{ github.actor }}"
            echo "The GSE is ${{ inputs.gse }}"
